# Generated by Django 5.2.13 on 2026-04-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0012_usermappreference_default_counties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('COORDINATOR', 'Coordinator'), ('ADMIN', 'Admin')], db_index=True, default='MEMBER', max_length=20),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
